spring:
  application:
    name: tlias-web-management
  #mysql连接配置
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tlias
    username: liuzibo
    password: 201654
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
pagehelper:
  reasonable: true
  helper-dialect: mariadb